plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  Collection: True
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
<<<<<<< HEAD:_config.yml
plugins:
  - jekyll-default-layout
=======
theme: just-the-docs
>>>>>>> fd2cd24469cb84f148f83f005e8d342f28477c7d:_congig.yml
